export const ROADMAP_OPTIONS = [
  { id: 'ai-agents', title: 'AI Agents', path: 'ai-agents/ai-agents.json' },
  { id: 'ai-data-scientist', title: 'AI Data Scientist', path: 'ai-data-scientist/ai-data-scientist.json' },
  { id: 'ai-engineer', title: 'AI Engineer', path: 'ai-engineer/ai-engineer.json' },
  { id: 'ai-red-teaming', title: 'AI Red Teaming', path: 'ai-red-teaming/ai-red-teaming.json' },
  { id: 'android', title: 'Android', path: 'android/android.json' },
  { id: 'angular', title: 'Angular', path: 'angular/angular.json' },
  { id: 'api-design', title: 'API Design', path: 'api-design/api-design.json' },
  { id: 'aspnet-core', title: 'ASP.NET Core', path: 'aspnet-core/aspnet-core.json' },
  { id: 'aws', title: 'AWS', path: 'aws/aws.json' },
  { id: 'backend', title: 'Backend', path: 'backend/backend.json' },
  { id: 'bi-analyst', title: 'BI Analyst', path: 'bi-analyst/bi-analyst.json' },
  { id: 'blockchain', title: 'Blockchain', path: 'blockchain/blockchain.json' },
  { id: 'cloudflare', title: 'Cloudflare', path: 'cloudflare/cloudflare.json' },
  { id: 'code-review', title: 'Code Review', path: 'code-review/code-review.json' },
  { id: 'computer-science', title: 'Computer Science', path: 'computer-science/computer-science.json' },
  { id: 'cpp', title: 'C++', path: 'cpp/cpp.json' },
  { id: 'cyber-security', title: 'Cyber Security', path: 'cyber-security/cyber-security.json' },
  { id: 'data-analyst', title: 'Data Analyst', path: 'data-analyst/data-analyst.json' },
  { id: 'data-engineer', title: 'Data Engineer', path: 'data-engineer/data-engineer.json' },
  { id: 'datastructures-and-algorithms', title: 'Data Structures & Algorithms', path: 'datastructures-and-algorithms/datastructures-and-algorithms.json' },
  { id: 'design-system', title: 'Design System', path: 'design-system/design-system.json' },
  { id: 'devops', title: 'DevOps', path: 'devops/devops.json' },
  { id: 'devrel', title: 'DevRel', path: 'devrel/devrel.json' },
  { id: 'docker', title: 'Docker', path: 'docker/docker.json' },
  { id: 'engineering-manager', title: 'Engineering Manager', path: 'engineering-manager/engineering-manager.json' },
  { id: 'flutter', title: 'Flutter', path: 'flutter/flutter.json' },
  { id: 'frontend', title: 'Frontend', path: 'frontend/frontend.json' },
  { id: 'full-stack', title: 'Full Stack', path: 'full-stack/full-stack.json' },
  { id: 'game-developer', title: 'Game Developer', path: 'game-developer/game-developer.json' },
  { id: 'git-github', title: 'Git & GitHub', path: 'git-github/git-github.json' },
  { id: 'golang', title: 'Golang', path: 'golang/golang.json' },
  { id: 'graphql', title: 'GraphQL', path: 'graphql/graphql.json' },
  { id: 'ios', title: 'iOS', path: 'ios/ios.json' },
  { id: 'java', title: 'Java', path: 'java/java.json' },
  { id: 'javascript', title: 'JavaScript', path: 'javascript/javascript.json' },
  { id: 'kubernetes', title: 'Kubernetes', path: 'kubernetes/kubernetes.json' },
  { id: 'linux', title: 'Linux', path: 'linux/linux.json' },
  { id: 'machine-learning', title: 'Machine Learning', path: 'machine-learning/machine-learning.json' },
  { id: 'mlops', title: 'MLOps', path: 'mlops/mlops.json' },
  { id: 'mongodb', title: 'MongoDB', path: 'mongodb/mongodb.json' },
  { id: 'nodejs', title: 'Node.js', path: 'nodejs/nodejs.json' },
  { id: 'php', title: 'PHP', path: 'php/php.json' },
  { id: 'postgresql-dba', title: 'PostgreSQL DBA', path: 'postgresql-dba/postgresql-dba.json' },
  { id: 'product-manager', title: 'Product Manager', path: 'product-manager/product-manager.json' },
  { id: 'prompt-engineering', title: 'Prompt Engineering', path: 'prompt-engineering/prompt-engineering.json' },
  { id: 'python', title: 'Python', path: 'python/python.json' },
  { id: 'qa', title: 'QA', path: 'qa/qa.json' },
  { id: 'react', title: 'React', path: 'react/react.json' },
  { id: 'react-native', title: 'React Native', path: 'react-native/react-native.json' },
  { id: 'redis', title: 'Redis', path: 'redis/redis.json' },
  { id: 'rust', title: 'Rust', path: 'rust/rust.json' },
  { id: 'server-side-game-developer', title: 'Server Side Game Developer', path: 'server-side-game-developer/server-side-game-developer.json' },
  { id: 'software-architect', title: 'Software Architect', path: 'software-architect/software-architect.json' },
  { id: 'software-design-architecture', title: 'Software Design & Architecture', path: 'software-design-architecture/software-design-architecture.json' },
  { id: 'spring-boot', title: 'Spring Boot', path: 'spring-boot/spring-boot.json' },
  { id: 'sql', title: 'SQL', path: 'sql/sql.json' },
  { id: 'system-design', title: 'System Design', path: 'system-design/system-design.json' },
  { id: 'technical-writer', title: 'Technical Writer', path: 'technical-writer/technical-writer.json' },
  { id: 'terraform', title: 'Terraform', path: 'terraform/terraform.json' },
  { id: 'typescript', title: 'TypeScript', path: 'typescript/typescript.json' },
  { id: 'ux-design', title: 'UX Design', path: 'ux-design/ux-design.json' },
  { id: 'vue', title: 'Vue', path: 'vue/vue.json' }
];
