import type { ProjectSeries } from '@/types'

export const PROJECT_SERIES: ProjectSeries[] = [
  {
    id: 'web-dev-fundamentals',
    title: 'Web Development Fundamentals',
    description: 'Master the core building blocks of modern web development with React and TypeScript. Start with a todo app and progress to a full data visualization dashboard.',
    icon: '🌐',
    color: '#3B82F6',
    projectIds: ['task-master-todo', 'weather-dashboard', 'ecommerce-product-filter', 'data-viz-dashboard'],
    totalProjects: 4,
    estimatedHours: 15,
    prerequisites: [],
    learningPath: [
      'React fundamentals and hooks',
      'TypeScript types and interfaces',
      'State management patterns',
      'API integration and data fetching',
      'Data visualization with Recharts',
    ],
  },
  {
    id: 'api-development-mastery',
    title: 'API Development Mastery',
    description: 'Learn how to consume and build APIs. Explore REST principles, HTTP methods, authentication, and advanced patterns.',
    icon: '🔌',
    color: '#10B981',
    projectIds: ['rest-api-explorer', 'weather-dashboard'],
    totalProjects: 2,
    estimatedHours: 9,
    prerequisites: ['Basic JavaScript/TypeScript knowledge'],
    learningPath: [
      'HTTP fundamentals (methods, status codes, headers)',
      'RESTful API design principles',
      'Async/await and error handling',
      'Authentication patterns (API keys, tokens)',
      'Rate limiting and caching strategies',
    ],
  },
  {
    id: 'data-visualization-path',
    title: 'Data Visualization Path',
    description: 'Transform raw data into compelling visual stories. Learn D3, Recharts, and data pipeline design.',
    icon: '📊',
    color: '#8B5CF6',
    projectIds: ['data-viz-dashboard', 'data-pipeline-etl'],
    totalProjects: 2,
    estimatedHours: 16,
    prerequisites: ['Basic React knowledge', 'Python basics'],
    learningPath: [
      'Data modeling and transformation',
      'Chart types and when to use them',
      'Interactive visualizations',
      'ETL pipeline design',
      'Data quality and validation',
    ],
  },
  {
    id: 'fullstack-developer-journey',
    title: 'Full-Stack Developer Journey',
    description: 'Go from frontend to full-stack. Build a complete web application with frontend, backend APIs, real-time features, and deployment.',
    icon: '🚀',
    color: '#F59E0B',
    projectIds: ['task-master-todo', 'rest-api-explorer', 'realtime-chat-app', 'ecommerce-product-filter'],
    totalProjects: 4,
    estimatedHours: 23,
    prerequisites: ['React basics', 'TypeScript basics'],
    learningPath: [
      'Full-stack architecture patterns',
      'RESTful API design and implementation',
      'Real-time communication with WebSockets',
      'Database integration',
      'Authentication and authorization',
      'Deployment and DevOps basics',
    ],
  },
  {
    id: 'mobile-development-path',
    title: 'Mobile Development Path',
    description: 'Build cross-platform mobile apps with React Native and Expo. Ship to iOS and Android from a single TypeScript codebase.',
    icon: '📱',
    color: '#EF4444',
    projectIds: ['expense-tracker-mobile'],
    totalProjects: 1,
    estimatedHours: 6,
    prerequisites: ['React knowledge', 'TypeScript basics'],
    learningPath: [
      'React Native vs React differences',
      'Mobile navigation patterns',
      'Native device features (camera, storage)',
      'Offline-first design',
      'App store deployment',
    ],
  },
]

export function getSeriesById(id: string): ProjectSeries | undefined {
  return PROJECT_SERIES.find(s => s.id === id)
}
