import type { PracticeKeyword } from './codeIntelligence.types'

export const JAVA_KEYWORDS: PracticeKeyword[] = [
  { label: 'public class Main', detail: 'Entry class for practice (no package)' },
  { label: 'public static void main(String[] args)', detail: 'Program entry point' },
  { label: 'System.out.println()', detail: 'Print a line to stdout' },
  { label: 'System.out.print()', detail: 'Print without newline' },
  { label: 'if', detail: 'Conditional branch' },
  { label: 'else', detail: 'Alternative branch' },
  { label: 'for', detail: 'For loop' },
  { label: 'while', detail: 'While loop' },
  { label: 'int', detail: 'Integer type' },
  { label: 'double', detail: 'Decimal type' },
  { label: 'String', detail: 'Text type (capital S)' },
  { label: 'boolean', detail: 'true / false type' },
  { label: 'ArrayList', detail: 'Resizable list (import java.util.ArrayList)' },
  { label: 'Math.max', detail: 'Larger of two numbers' },
  { label: 'Math.min', detail: 'Smaller of two numbers' },
  { label: 'Math.pow', detail: 'Power: Math.pow(base, exp)' },
  { label: 'Integer.parseInt', detail: 'Parse text to int (no stdin in practice yet)' },
  { label: 'Scanner', detail: 'Stdin not supported in practice — use in-code variables' },
  { label: 'return', detail: 'Return from method' },
  { label: 'break', detail: 'Break loop' },
  { label: 'continue', detail: 'Continue loop' },
  { label: 'true', detail: 'Boolean true' },
  { label: 'false', detail: 'Boolean false' },
  { label: '// comment', detail: 'Single-line comment' },
  { label: '/* block comment */', detail: 'Multi-line comment' },
]
